# Site settings
gems:
  - jekyll-paginate

title: Stanford Concert Network
url: https://stanfordconcertnetwork.github.io
events:
  - title: 2018 Frost Music & Arts Festival
    date: Saturday May 19th
    location: Stanford Football Stadium
    link: https://www.facebook.com/events/225336938025428

paginate: 5
paginate_path: "/news/page:num"
