# Site settings
title: Stanford Concert Network
url: https://stanfordconcertnetwork.github.io
events:
  - title: BJ the Chicago Kid at Black Love
    date: 6:30PM Friday Feb 17th
    location: Toyon Lounge
    link: https://www.facebook.com/events/607527856122808/
  - title: Jerry Folk at Dance Marathon
    date: 11PM Saturday Feb 18th
    location: AOERC
    link: https://www.facebook.com/events/194733154337407/
