# Site settings
gems:
  - jekyll-paginate

title: Stanford Concert Network
url: https://stanfordconcertnetwork.github.io
source: ./src
events:
  - title: 2017 Frost Music & Arts Festival
    date: Saturday May 20th
    location: Stanford Football Stadium
    link: https://www.facebook.com/events/928300317272746/

paginate: 5
paginate_path: "/news/page:num"
