# Site settings
title: Stanford Concert Network
url: https://stanfordconcertnetwork.github.io
event:
  title: Oshi, XXYYXX, 20syl
  date: 8PM Sep 30
  location: EBF
  link: https://facebook.com/events/EVENT
